@startuml
!theme plain
autonumber

actor Joueur
participant "LabyJeu" as LabyJeu
participant "Fantôme" as Fantome
participant "Labyrinthe" as Labyrinthe
participant "Héros" as Heros

Joueur -> LabyJeu : update()
activate LabyJeu

LabyJeu -> Heros : déplacer(direction)
activate Heros

Heros -> Labyrinthe : getSuivant(x,y,direction)
activate Labyrinthe
Labyrinthe --> Heros : [nx,ny]
deactivate Labyrinthe

Heros -> Fantome : estPrésent(nx,ny)
activate Fantome
Fantome --> Heros : false (traverse pas héros)
deactivate Fantome

Heros -> Heros : mettreÀJourPosition(nx,ny)

deactivate Heros

LabyJeu -> Fantome : déplacer()
activate Fantome

Fantome -> Fantome : choisirDirectionAléatoire()
Fantome -> Labyrinthe : getSuivant(x,y,direction)
activate Labyrinthe
Labyrinthe --> Fantome : [mx,my] (peut être mur)
deactivate Labyrinthe

Fantome -> LabyJeu : estEntitéPrésente(mx,my)
activate LabyJeu
LabyJeu --> Fantome : false (case libre)
deactivate LabyJeu

    Fantome -> Fantome : x = mx, y = my
    Fantome -> Fantome : annulerDéplacement()

deactivate Fantome
deactivate LabyJeu
@enduml