@startuml
title Fin du jeu : Mort du héros

autonumber

Participant "Monstre" as monstre
Participant "Heros" as heros
Participant "Labyrinthe" as laby

activate monstre
monstre -> monstre : attaquer()
activate monstre

monstre -> heros : subirDegats(1)
activate heros
heros --> monstre : void
deactivate heros

monstre -> laby : etreFini()
activate laby

laby -> heros : etreVivant()
activate heros
heros --> laby : false
deactivate heros

laby --> monstre : true
deactivate laby

deactivate monstre
deactivate monstre
@enduml