@startuml
'https://plantuml.com/sequence-diagram

autonumber

Participant "LabyJeu" as labyjeu
Participant "Heros" as heros
Participant "Amulette" as amulette

activate labyjeu
labyjeu ->  heros : etreFini() :

activate heros
heros -> amulette : etrePresent(int, int)

activate amulette
heros <-- amulette : boolean
deactivate amulette
heros -> heros : setAmulette()
activate heros

heros <-- heros
deactivate heros

labyjeu <-- heros

deactivate heros
deactivate labyjeu
@enduml