@startuml
title Victoire du héros

autonumber

Participant "LabyJeu" as labyjeu
Participant "Labyrinthe" as laby
Participant "Heros" as heros

activate labyjeu
labyjeu -> laby : etreFini()
activate laby

laby -> heros : etreVivant()
activate heros
heros --> laby : true
deactivate heros

laby -> heros : remplirConditionVictoire()
activate heros
heros -> heros : getAmulette()
activate heros
heros --> heros : true
deactivate heros
heros --> laby : true
deactivate heros

laby --> labyjeu : true
deactivate laby

deactivate labyjeu
@enduml