@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant "Main" as main
participant "Monstre" as monstre
participant "Heros" as heros
participant "Labyrinthe" as laby

activate main
main -> monstre : deplacer(String)
activate monstre

monstre -> heros : attaquer()
activate heros
heros --> monstre : aTape boolean
deactivate heros

alt aTape == false
    monstre -> monstre : deplacementAleatoire()
    monstre <-- monstre : actionAleatoire : String

    monstre -> laby : getSuivant(x, y, action)
    activate laby
    laby --> monstre : suivant[]
    deactivate laby

    monstre -> laby : getMur(suivant[0], suivant[1])
    activate laby
    laby --> monstre : estMur : boolean
    deactivate laby

    monstre -> heros : etrePresent(suivant[0],suivant[1])
    heros --> monstre : estPresent : boolean

    alt !estMur && !estPresent
        monstre -> monstre : monstre.x = suivant[0]
        monstre -> monstre : monstre.y = suivant[1]
    end
end

monstre --> main : void
deactivate monstre
deactivate main

@enduml