@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant "Main" as main
participant "Monstre" as monstre
participant "Heros" as heros
participant "Labyrinthe" as laby

main -> monstre: deplacer()
activate monstre

monstre -> monstre: verifierProximiteHeros()
activate monstre #DarkSalmon

alt heroAPortee == true
    monstre -> heros: attaquer(degats)
    activate heros
    heros -> heros: subirDegats(degats)
    heros --> monstre: confirmation
    deactivate heros

else heroAPortee == false
    monstre -> laby: getMur(suivant_x, suivant_y)
    activate laby
    laby --> monstre: mur_present
    deactivate laby

    alt mur_present == false
        monstre -> monstre: deplacementAleatoire()
    end
end

deactivate monstre
deactivate monstre

@enduml