@startuml
'https://plantuml.com/sequence-diagram

autonumber

Main -> Monstre: deplacerMonstre()
alt heroProximite = true
Monstre -> Monstre : attaquerMonstre(cible, degat)

else attaque = true

end



@enduml