@startuml
title Déplacement vers le héros

autonumber

Participant "Bestiaire" as bestiaire
Participant "Monstre" as monstre
Participant "Labyrinthe" as laby
Participant "Heros" as heros

activate bestiaire
bestiaire -> monstre : deplacerVersHeros()
activate monstre

monstre -> monstre : calculerDistance()
activate monstre
monstre -> laby : getPj()
activate laby
laby -> heros : getX(), getY()
activate heros
heros --> laby : x, y
deactivate heros
laby --> monstre : position héros
deactivate laby
monstre --> monstre : [type, diff]
deactivate monstre

monstre -> monstre : choisirDeplacement()
activate monstre
monstre --> monstre : direction
deactivate monstre

monstre -> monstre : deplacer(direction)
activate monstre

monstre -> monstre : attaquer()
monstre -> monstre : setX(), setY()

deactivate monstre
monstre <-- monstre
monstre --> bestiaire
deactivate bestiaire
@enduml