@startuml
'https://plantuml.com/sequence-diagram

autonumber

Main -> Monstre : deplacerVersHeros()
activate Monstre

Monstre -> Monstre : choisirDeplacement()
activate Monstre


Monstre -> Monstre : calculerDistance()
activate Monstre

Monstre -> Heros : getX()
activate Heros
Monstre <-- Heros : int
deactivate Heros

Monstre -> Heros : getY()
activate Heros
Monstre <-- Heros : int
deactivate Heros

Monstre <-- Monstre: int[]
deactivate Monstre
Monstre <-- Monstre : String action

deactivate Monstre

Monstre -> Monstre: deplacer(action)
activate Monstre
Monstre <-- Monstre: void


deactivate Monstre

Main <-- Monstre : void

@enduml