@startuml
'https://plantuml.com/sequence-diagram

autonumber

Main -> Monstre : deplacerVersHeros()

Monstre -> Monstre : calculerDistance()


activate Monstre

Monstre -> Perso : getX()
activate Perso
Monstre <-- Perso : int
deactivate Perso

Monstre -> Perso : getY()
activate Perso
Monstre <-- Perso : int
deactivate Perso

Monstre <-- Monstre : int[]
deactivate Monstre


@enduml